/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.views;

/**
 *
 * @author mealf
 */
public class genioFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(genioFrame.class.getName());

    /**
     * Creates new form genioFrame
     */
    public genioFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto1 = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        spnValor = new javax.swing.JSpinner();
        lblGenio = new javax.swing.JLabel();
        lblBalao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTexto1.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        lblTexto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTexto1.setText("Vou pensar em um numero de 1 a 5");
        getContentPane().add(lblTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, 20));

        lblTexto2.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        lblTexto2.setText("Adivinhe!!");
        getContentPane().add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        lblValor.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        lblValor.setText("Valor");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        btnPalpite.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        btnPalpite.setText("Palpite");
        btnPalpite.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPalpite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPalpite.addActionListener(this::btnPalpiteActionPerformed);
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 110, 30));

        spnValor.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        spnValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        spnValor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        spnValor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spnValor.setOpaque(true);
        getContentPane().add(spnValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genio - Copia.png"))); // NOI18N
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        lblBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caixa_de_dialogo.png"))); // NOI18N
        getContentPane().add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //botão de palpite
    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
        //pega o valor que o usuário seleciou no spinner e transforma em int
        int numeroEscolhido = (int) spnValor.getValue();
        
        //gera um numero aleátorio entre 1 e 5
        int numeroGenio = (int) (Math.random() * 5) + 1;
        
        //compara se os dois numeros são iguais
        if(numeroEscolhido == numeroGenio){
            lblTexto1.setText(" ");
            lblTexto2.setText("Acertou!!");
        } else {
            lblTexto1.setText("Errou!! O numero que pensei era " + numeroGenio);
            lblTexto2.setText("Tente de novo");
        }
        
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new genioFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblValor;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
